[book]
authors = ["Mark Veltzer <mark.veltzer@gmail.com>"]
language = "en"
src = "docs"
title = "RSType - Rust Typing Trainer"

[build]
build-dir = "_site"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rstype"
edit-url-template = "https://github.com/veltzer/rstype/edit/master/docs/{path}"
